name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate JUnit report
        run: |
          npm install --save-dev jest-junit
          npx jest --ci --reporters=default --reporters=jest-junit

      - name: Upload test results artifact
        uses: actions/upload-artifact@v4
        with:
          name: jest-junit-report
          path: ./junit.xml

      - name: Display test results
        if: always()
        run: |
          if [ -f junit.xml ]; then
            cat junit.xml
          else
            echo "No JUnit test report found."
          fi
